ARG CUDA_VERSION=12.2.2
ARG CUDNN_VERSION=8
ARG UBUNTU_VERSION=22.04
FROM nvidia/cuda:${CUDA_VERSION}-cudnn${CUDNN_VERSION}-devel-ubuntu${UBUNTU_VERSION}

#ARG OPENCV_VERSION=4.8.1
ARG OPENCV_VERSION=4.x

# Install the necessary packages
RUN apt update && \
    apt upgrade -y && \
    apt install -y build-essential cmake pkg-config && \
    apt install -y python3-dev python3-pip && \
    apt install -y ffmpeg && \
    apt install -y curl jq git

WORKDIR /opencv_cudnn_build

RUN git clone https://github.com/opencv/opencv.git --branch ${OPENCV_VERSION} && \
    git clone https://github.com/opencv/opencv_contrib.git --branch ${OPENCV_VERSION}

RUN pip3 install numpy

WORKDIR /opencv_cudnn_build/opencv/build

ARG CUDA_ARCH_BIN=7.5

RUN cmake -D CMAKE_BUILD_TYPE=RELEASE \
  -D CMAKE_INSTALL_PREFIX=/usr/local \
  -D INSTALL_PYTHON_EXAMPLES=ON \
  -D INSTALL_C_EXAMPLES=OFF \
  -D OPENCV_ENABLE_NONFREE=ON \
  -D WITH_CUDA=ON \
  -D WITH_CUDNN=ON \
  -D OPENCV_DNN_CUDA=ON \
  -D ENABLE_FAST_MATH=1 \
  -D CUDA_FAST_MATH=1 \
  -D CUDA_ARCH_BIN=${CUDA_ARCH_BIN} \
  -D WITH_CUBLAS=1 \
  -D OPENCV_EXTRA_MODULES_PATH=/opencv_cudnn_build/opencv_contrib/modules \
  -D HAVE_opencv_python3=ON \
  -D PYTHON_EXECUTABLE=/usr/bin/python3 \
  -D BUILD_EXAMPLES=ON ..

RUN make -j8 && \
    make install && \
    ldconfig
